// Please Note The id is important!
// The id can be anything but unique
// @Ahmad Khidir


export const products = {
    meals: [
        {   
            id: 1,
            name: 'jollof rice',
            label: 'per portion',
            price: 300,
            image: require('../assets/images/Jollofrice.jpeg'),
        },
        {
            id: 2,
            name: 'fried rice',
            label: 'per portion',
            price: 350,
            image: require('../assets/images/Friedrice.jpeg'),
        },
        {
            id: 3,
            name: 'Spaghetti',
            label: 'per portion',
            price: 300,
            image: require('../assets/images/spaghetti.jpeg'),
        },
        {
            id: 4,
            name: 'Noodles',
            label: 'per 70g',
            price: 250,
            image: require('../assets/images/noodles.jpeg'),
        },
        {
            id: 42,
            name: 'White rice',
            label: 'per portion',
            price: 300,
            image: require('../assets/images/rice.png'),
        },
        {
            id: 5,
            name: 'Yam Porridge',
            label: 'per portion',
            price: 350,
            image: require('../assets/images/Porridge.jpeg'),
        },
        {
            id: 6,
            name: 'french fries',
            label: 'per portion',
            price: 500,
            image: require('../assets/images/fries.jpeg'),
        },
        {
            id: 7,
            name: 'Cooked Yam',
            label: 'per portion',
            price: 300,
            image: require('../assets/images/yam.jpeg'),
        },
    ],
    sides: [
        {
            id: 8,
            name: 'plantain',
            label: 'per 4 pieces',
            price: 100,
            image: require('../assets/images/13.png'),
        },
        {
            id: 39,
            name: 'moin-moin',
            label: 'per wrap',
            price: 250,
            image: require('../assets/images/moinmoin.jpeg'),
        },
        {
            id: 40,
            name: 'coleslaw',
            label: 'per serving',
            price: 200,
            image: require('../assets/images/coleslaw.jpeg'),
        },
        {
            id: 17,
            name: 'Egg sauce',
            label: 'per portion',
            price: 300,
            image: require('../assets/images/Egg-Sauce.jpeg'),
        },
    ],
    swallows: [
        {
            id: 9,
            name: 'semolina',
            label: 'per wrap',
            price: 200,
            image: require('../assets/images/1.jpg'),
        },
        {
            id: 10,
            name: 'eba',
            label: 'per wrap',
            price: 200,
            image: require('../assets/images/eba.jpeg'),
        },
        {
            id: 11,
            name: 'amala',
            label: 'per wrap',
            price: 200,
            image: require('../assets/images/amala.jpeg'),
        },
        {
            id: 12,
            name: 'poundo',
            label: 'per wrap',
            price: 300,
            image: require('../assets/images/poundo.jpeg'),
        },
    ],
    protein: [
        {
            id: 13,
            name: 'chicken',
            label: 'per piece',
            price: 500,
            image: require('../assets/images/11.jpg'),
        },
        {
            id: 14,
            name: 'beef',
            label: 'per piece',
            price: 300,
            image: require('../assets/images/beef.jpeg'),
        },
        {
            id: 15,
            name: 'ponmo',
            label: 'per piece',
            price: 300,
            image: require('../assets/images/ponmo.jpeg'),
        },
        {
            id: 41,
            name: 'Turkey',
            label: 'per piece',
            price: 800,
            image: require('../assets/images/turkey.jpeg'),
        },
        {
            id: 16,
            name: 'titus fish',
            label: 'per piece',
            price: 500,
            image: require('../assets/images/titus.png'),
        },
        {
            id: 18,
            name: 'Boiled egg',
            label: 'per piece',
            price: 100,
            image: require('../assets/images/egg.jpeg'),
        },
    ],
    soups: [
        {
            id: 19,
            name: 'egusi',
            label: 'per portion',
            price: 200,
            image: require('../assets/images/egusi.png'),
        },
        {
            id: 20,
            name: 'efo riro',
            label: 'per portion',
            price: 200,
            image: require('../assets/images/efo-riro.png'),
        },
        {
            id: 21,
            name: 'ewedu',
            label: 'per portion',
            price: 200,
            image: require('../assets/images/ewedu.png'),
        },
        {
            id: 22,
            name: 'chicken pepper soup',
            label: 'per plate',
            price: 1500,
            image: require('../assets/images/chicken-peppersoup.png'),
        },
        {
            id: 23,
            name: 'catfish pepper soup',
            label: 'per plate',
            price: 2000,
            image: require('../assets/images/catfish-peppersoup.png'),
        },
        {
            id: 24,
            name: 'assorted pepper soup',
            label: 'per plate',
            price: 2000,
            image: require('../assets/images/assorted-peppersoup.png'),
        },
    ],
    grills: [
        {
            id: 25,
            name: 'asun',
            label: 'per portion',
            price: 500,
            image: require('../assets/images/7.jpg'),
        },
        {
            id: 26,
            name: 'sharwarma',
            label: 'per wrap',
            price: 1200,
            image: require('../assets/images/shawarma.jpeg'),
        },
        {
            id: 27,
            name: 'sharwarma (extra chicken)',
            label: 'per wrap',
            price: 1500,
            image: require('../assets/images/shawarma.jpeg'),
        },
        {
            id: 28,
            name: 'grilled chicken',
            label: 'per serving',
            price: 1500,
            image: require('../assets/images/barbecue_chicken.jpeg'),
        },
        {
            id: 29,
            name: 'chicken & chips',
            label: 'per serving',
            price: 1500,
            image: require('../assets/images/6.png'),
        },
        {
            id: 30,
            name: 'barbecue fish',
            label: 'per plate',
            price: 2500,
            image: require('../assets/images/9.jpeg'),
        },
    ],
    combos: [
        {
            id: 31,
            name: 'noodles and sausage with fried egg',
            label: 'per plate',
            price: 800,
            image: require('../assets/images/noodles-egg.png'),
        },
        {
            id: 32,
            name: 'Yam and egg sauce with plantain',
            label: 'per plate',
            price: 800,
            image: require('../assets/images/yam-sauce.jpeg'),
        },
    ],
    drinks: [
        {
            id: 33,
            name: 'Bottled Water',
            label: 'per bottle',
            price: 100,
            image: require('../assets/images/water.png'),
        },
        {
            id: 34,
            name: 'Coca Cola',
            label: 'per bottle',
            price: 150,
            image: require('../assets/images/coke.png'),
        },
        {
            id: 35,
            name: 'Pepsi',
            label: 'per bottle',
            price: 150,
            image: require('../assets/images/pepsi.png'),
        },
        {
            id: 36,
            name: 'Maltina',
            label: 'per can/bottle',
            price: 250,
            image: require('../assets/images/malt.png'),
        },
        {
            id: 37,
            name: 'Chamdor Wine',
            label: 'per bottle',
            price: 2500,
            image: require('../assets/images/chamdor.png'),
        },
        {
            id: 38,
            name: 'Veleta Wine',
            label: 'per bottle',
            price: 2000,
            image: require('../assets/images/veleta.png'),
        }
    ]
}